### ISSUE TITLE
Suggest to use lombok in the project

### ISSUE THREAD

**Issue by zhfkt** [flashvayne/mysql-mybatis-pagination#1]
If possible, we could use lombok in this project so that the syntax of redundant getter and setter methods could be avoided.

https://github.com/flashvayne/mysql-mybatis-pagination/blob/edd39df0354611665e1754af65420731c71ebf47/src/main/java/com/github/flashvayne/dto/PageInfo.java#L15

Thank you.

**Comment by flashvayne** [comment]
Thank you very much for your suggestion.
I have simplified code using Lombok.
see [commit](https://github.com/flashvayne/mysql-mybatis-pagination/commit/f797f0ee2365d749d8d66885078e97ab23de03bd)
